name: cyclopsys
description: "Optical Character Recognition & Text to Speech Service for Visually impaired people."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.10.0+1 
  permission_handler: ^11.2.0
  image_picker: ^1.0.0
  google_mlkit_text_recognition: ^0.8.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
